variables:
  - group: Global Pipeline Settings
  - group: Discord Webhook Publishing Variables
  - name: project.folder
    value: 'XRTK'
  - name: project.name
    value: 'XRTK-Core'
  - name: package.name
    value: 'com.xrtk.core'
  - name: project.upmSha
    value: ''
  - name: EditorPath
    value: ''
  - name: LogDirectory
    value: ''

name: $(package.name)-${{ coalesce( variables['System.PullRequest.PullRequestNumber'], variables['Build.SourceBranchName'], 'ERROR') }}-$(Date:yyyyMMdd)$(Rev:.r)

# trigger:
#   batch: true
#   branches:
#     include:
#     - master
#   paths:
#     include:
#       - docfx_project
#       - $(project.name)/*
#     exclude:
#       - '*'
#       - $(project.name)/Packages/$(package.name)/README.md
#       - $(project.name)/Packages/$(package.name)/LICENSE.md
#       - $(project.name)/Packages/$(package.name)/.github/*

pr:
  autoCancel: true
  branches:
   include:
     - master
     - development
     - feature/*
  paths:
    include:
    - $(project.name)/*
    exclude:
      - '*'
      - $(project.name)/Packages/$(package.name)/README.md
      - $(project.name)/Packages/$(package.name)/LICENSE.md
      - $(project.name)/Packages/$(package.name)/.github/*

extends:
  template: azure_pipelines/common.yml