# XRTK Azure Pipelines build configuration

resources:
  repositories:
    - repository: pipeline_repo
      type: github
      name: XRTK/AzurePipelines
      endpoint: XRTK

variables:
  project.name: 'XRTK-Core'
  project.upmSha: ''
  package.name: 'com.xrtk.core'
  package.version: ''
  EditorPath: ''
  LogDirectory: ''
  # Unity -buildTarget command line args https://docs.unity3d.com/Manual/CommandLineArguments.html
  # 'StandaloneWindows', 'StandaloneWindows64', 'WSAPlayer', 'XBoxOne'
  # 'StandaloneOSX', 'iOS', 'tvOS'
  # 'StandaloneLinux64'
  # 'PSP2', 'PS4'
  # 'N3DS', 'WiiU', 'Switch'
  # 'Android', 'WebGL', 'Lumin'
  # TODO: Only use XRTK defined platform targets for build
  unity.build.targets: '"StandaloneWindows64", "WSAPlayer", "Android", "Lumin", "WebGL"'
  ${{ if eq( variables['build.reason'], 'PullRequest' ) }}:
    date: ''
  ${{ if ne( variables['build.reason'], 'PullRequest' ) }}:
    date: ${{ '$(Date:yyyyMMdd)' }}
  isReleaseBuild: $[ and( eq(variables['Build.SourceBranchName'], 'master'), or( eq(variables['build.reason'], 'BatchedCI'), eq(variables['build.reason'], 'Manual') ) ) ]
  isPreviewBuild: $[ and( eq(variables['System.PullRequest.TargetBranch'], 'master'), eq(variables['build.reason'], 'PullRequest') ) ]

name: $(package.name) ${{ coalesce( variables['date'], '$(System.PullRequest.PullRequestNumber)', '$(Date:yyyyMMdd)' ) }}$(Rev:.r)

pr:
  autoCancel: true
  branches:
   include:
     - master
     - development
     - feature/*
  paths:
    include:
    - azure-pipelines.yml
    - azure_pipelines/*
    - XRTK-Core/*
    - Submodules/*
    exclude:
      - '*'
      - XRTK-Core/Packages/com.xrtk.core/README.md
      - XRTK-Core/Packages/com.xrtk.core/LICENSE.md
      - XRTK-Core/Packages/com.xrtk.core/.github/*

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - azure-pipelines.yml
      - azure_pipelines/*
      - XRTK-Core/*
      - Submodules/*
    exclude:
      - '*'
      - XRTK-Core/Packages/com.xrtk.core/README.md
      - XRTK-Core/Packages/com.xrtk.core/LICENSE.md
      - XRTK-Core/Packages/com.xrtk.core/.github/*

extends:
  template: common.yml@pipeline_repo
