parameters:
  - name: 'platform'
    type: object
    default:
      windows:
  - name: 'image'
    type: string
    default: 'windows-latest'
  - name: 'components'
    type: string
    default:
      - Windows
      - Windows_IL2CPP
      - UWP_IL2CPP
      - Android
  - name: 'targets'
    type: string
    default:
      - StandaloneWindows64
      - WSAPlayer
      - Android

stages:
- stage:
  displayName: ${{ format('{0} Build', parameters.platform, parameters.image) }}
  jobs:
    - job:
      pool:
        name: 'Azure Pipelines'
        vmImage: ${{ parameters.image }}
        demands:
          - unity -equals true
      steps:
      - checkout: self
        submodules: recursive
      - template: steps/install-unity.yml
      - ${{ each pair in parameters.targets }}:
        - template: steps/run-unity-tests.yml
          parameters:
            target: ${{ pair.value }}
        - template: steps/build-unity-player.yml
          parameters:
            target: ${{ pair.value }}
      - template: steps/release-unity.yml
