stages:
- stage:
  displayName: ${{ format('{0} build ({1})', parameters.platform, parameters.image) }}
  jobs:
    - job:
      pool:
        name: 'Azure Pipelines'
        vmImage: ${{ parameters.image }}
        demands:
          - unity -equals true
      steps:
      - checkout: self
        submodules: recursive
      - template: steps/install-unity.yml
      - ${{ each pair in parameters.targets }}:
        - template: steps/run-unity-tests.yml
          parameters:
            target: ${{ pair.value }}
        - template: steps/build-unity-player.yml
          parameters:
            target: ${{ pair.value }}
      - template: steps/release-unity.yml
