parameters:
  - name: platform
    type: object
    default:
      windows:
  - name: image
    type: string
    default: ''
  - name: components
    type: string
    default: ''
  - name: targets
    type: string
    default:
    - 'StandaloneWindows64'
    - 'WSAPlayer'
    - 'Android'

stages:
- stage:
  displayName: ${{ format('{0} build', parameters.platform, parameters.image) }}
  jobs:
    - job:
      pool:
        name: 'Azure Pipelines'
        vmImage: ${{ parameters.image }}
        demands:
          - unity -equals true
      steps:
      - checkout: self
        submodules: recursive
      - template: steps/install-unity.yml
        parameters: ${{ parameters.components }}
      # - ${{ each item in parameters.targets }}:
      #   - template: steps/run-unity-tests.yml
      #     parameters:
      #       target: ${{ item.value }}
      #   - template: steps/build-unity-player.yml
      #     parameters:
      #       target: ${{ item.value }}
      - template: steps/release-unity.yml
