stages:
- stage:
  displayName: ${{ format('{0} build', parameters.platform) }}
  jobs:
    - job:
      displayName: ${{ format('{0}', parameters.image) }}
      pool:
        name: 'Azure Pipelines'
        vmImage: ${{ parameters.image }}
        demands:
          - unity -equals true
      steps:
      - checkout: self
        submodules: recursive
      - template: steps/install-unity.yml
        parameters:
          components: ${{ parameters.components }}
      - ${{ each item in parameters.targets }}:
        - template: steps/run-unity-tests.yml
          parameters:
            target: ${{ item }}
        - template: steps/build-unity-player.yml
          parameters:
            target: ${{ item }}
      - template: steps/release-unity.yml
