parameters:
  - name: os
    type: object
    default:
      windows:
        image: windows-latest
        # TODO: Only use XRTK defined platforms for build and install the correct modules and switch to the correct targets as needed
        # Unity Hub Modules for Windows Editor: android, ios, appletv linux, mac-mono universal-windows-platform, vuforia-ar, webgl, windows-il2cpp, facebook-games, lumin, android-sdk-ndk-tools
        modules: '"windows-il2cpp", "universal-windows-platform", "android"'
        targets:
          # Unity -buildTarget command line args https://docs.unity3d.com/Manual/CommandLineArguments.html
          # 'StandaloneOSX', 'StandaloneWindows', 'iOS', 'Android', 'StandaloneLinux', 'StandaloneWindows64', 'WebGL',
          # 'WSAPlayer', 'StandaloneLinux64', 'StandaloneLinuxUniversal', 'Tizen', 'PSP2', 'PS4', 'XBoxOne', 'N3DS', 'WiiU', 'tvOS', 'Switch', 'Lumin'
        - StandaloneWindows64
        - Android
      macOS:
        image: macOS-latest
        # Unity Hub Modules for MacOS Editor: android, ios, appletv linux, mac-mono universal-windows-platform, vuforia-ar, webgl, windows-il2cpp, facebook-games, lumin, android-sdk-ndk-tools
        modules: '"Mac", "Mac_IL2CPP"'
        targets:
        - StandaloneOSX
      linux:
        image: ubuntu-latest
        modules: '"Linux"'
        targets:
        - StandaloneLinux64

stages:
  - template: stages/unity-build.yml
    parameters:
      platform: windows
      ${{ insert }}: ${{ parameters.os.windows }}
  - template: stages/publish.yml
