parameters:
  - name: os
    type: object
    default:
      Windows:
        image: windows-latest
        components: '"Windows", "Windows_IL2CPP", "UWP_IL2CPP", "Android"'
        # https://github.com/microsoft/unitysetup.powershell installer component options
        # Windows, Windows_IL2CPP, UWP_IL2CPP, Lumin, Android, iOS, Mac, Mac_IL2CPP , WebGL
        targets:
          - 'StandaloneWindows64'
          - 'WSAPlayer'
          - 'Android'
        # Unity -buildTarget command line args https://docs.unity3d.com/Manual/CommandLineArguments.html
        # 'StandaloneOSX', 'StandaloneWindows', 'iOS', 'Android', 'StandaloneLinux', 'StandaloneWindows64', 'WebGL',
        # 'WSAPlayer', 'StandaloneLinux64', 'StandaloneLinuxUniversal', 'Tizen', 'PSP2', 'PS4', 'XBoxOne', 'N3DS', 'WiiU', 'tvOS', 'Switch', 'Lumin'
      MacOS:
        image: macOS-latest
        components: '"Mac", "Mac_IL2CPP"'
        targets:
          - 'StandaloneOSX'
      Linux:
        image: ubuntu-latest
        components: '"Linux"'
        targets:
          - 'StandaloneLinux64'

stages:
  - template: stages/unity-build.yml
    parameters:
      platform: Windows
      ${{ insert }}: ${{ parameters.os.windows }}

# - template: stages/publish.yml
#   parameters:
#     shouldRun: and(eq(variables[build.reason], 'IndividualCI'), eq(variables[build.sourceBranchName], 'master'))
#     vmImage: ${{ parameters.os.windows.image }}
